export const ACTUAL_URLS: Record<string, string> = {
    "Antitrust Enforcement and Intellectual Property Rights Chapter 1": "https://www.justice.gov/atr/chapter-1-strategic-use-licensing-unilateral-refusals-license-patents",
    "Antitrust Enforcement and Intellectual Property Rights Chapter 2": "https://www.justice.gov/atr/chapter-2-competition-concerns-when-patents-are-incorporated-collaboratively-set-standards",
    "Antitrust Enforcement and Intellectual Property Rights Chapter 3": "https://www.justice.gov/atr/chapter-3-antitrust-analysis-portfolio-cross-licensing-agreements-and-patent-pools",
    "Antitrust Enforcement and Intellectual Property Rights Chapter 4": "https://www.justice.gov/atr/chapter-4-variations-intellectual-property-licensing-practices",
    "Antitrust Enforcement and Intellectual Property Rights Chapter 5": "https://www.justice.gov/atr/chapter-5-antitrust-issues-tying-and-bundling-intellectual-property-rights",
    "Antitrust Enforcement and Intellectual Property Rights Chapter 6": "https://www.justice.gov/atr/chapter-6-competitive-issues-regarding-practices-extend-market-power-conferred-patent-beyond-its",
    "Antitrust Guidelines for Business Activities Affecting Workers": "https://www.justice.gov/atr/guidelines-and-policy-statements-0",
    "Antitrust Guidelines for International Enforcement and Cooperation": "https://www.justice.gov/atr/guidelines-and-policy-statements-0",
    "Antitrust Guidelines for the Licensing of Intellectual Property": "https://www.justice.gov/atr/guidelines-and-policy-statements-0",
    "Antitrust Policy Statement on Sharing of Cybersecurity Information": "https://www.justice.gov/atr/guidelines-and-policy-statements-0",
    "Title 7 - Antitrust": "https://www.justice.gov/jm/title-7-antitrust",
    "Dodd-Frank Wall Street Reform and Consumer Protection Act": "https://www.sec.gov/rules-regulations/statutes-regulations",
    "Investment Advisers Act of 1940": "https://www.sec.gov/rules-regulations/statutes-regulations",
    "Investment Company Act of 1940": "https://www.sec.gov/rules-regulations/statutes-regulations",
    "Jumpstart Our Business Startups (JOBS) Act": "https://www.sec.gov/rules-regulations/statutes-regulations",
    "SEC Rules and Regulations part 200": "https://www.ecfr.gov/current/title-17/chapter-II/part-200",
    "SEC Rules and Regulations part 201": "https://www.ecfr.gov/current/title-17/chapter-II/part-201",
    "SEC Rules and Regulations part 202": "https://www.ecfr.gov/current/title-17/chapter-II/part-202",
    "SEC Rules and Regulations part 203": "https://www.ecfr.gov/current/title-17/chapter-II/part-203",
    "SEC Rules and Regulations part 204": "https://www.ecfr.gov/current/title-17/chapter-II/part-204",
    "SEC Rules and Regulations part 205": "https://www.ecfr.gov/current/title-17/chapter-II/part-205",
    "SEC Rules and Regulations part 209": "https://www.ecfr.gov/current/title-17/chapter-II/part-209",
    "SEC Rules and Regulations part 210": "https://www.ecfr.gov/current/title-17/chapter-II/part-210",
    "SEC Rules and Regulations part 227": "https://www.ecfr.gov/current/title-17/chapter-II/part-227",
    "SEC Rules and Regulations part 229": "https://www.ecfr.gov/current/title-17/chapter-II/part-229",
    "Sarbanes-Oxley Act of 2002": "https://www.sec.gov/rules-regulations/statutes-regulations",
    "Securities Act of 1933": "https://www.sec.gov/rules-regulations/statutes-regulations",
    "Securities Exchange Act of 1934": "https://www.sec.gov/rules-regulations/statutes-regulations",
    "Trust Indenture Act of 1939": "https://www.sec.gov/rules-regulations/statutes-regulations",
  };
  